name: dart_launchdarkly
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/QuirijnGB/dart-launchdarkly
author: quirijngb <email@example.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.30
